import Generaltag from "./components/inputTypes/generalTag";
import PriceNumber from "./components/inputTypes/PriceNumber";

const inputMapper = {
  Gender: {
    component: Generaltag,
    data: ["Femer", "Mashkull"],
    rules: [
      "is",
      "is not",
      "starts with",
      "ends with",
      "contains",
      "does not contain",
    ],
  },
  Brand: {
    component: Generaltag,
    data: [
      "KANLE",
      "LIT",
      "GRUNBERG",
      "CROSBY",
      "COX BORBA",
      "BETSY",
      "TESORO",
      "STYLISH",
      "SKECHERS",
      "MOLECA",
    ],
    rules: [
      "is",
      "is not",
      "starts with",
      "ends with",
      "contains",
      "does not contain",
    ],
  },
  Category: {
    component: Generaltag,
    data: [
      "Patika",
      "Sandale",
      "Cizme",
      "Papuqe",
      "Papuqe Verore",
      "Cante",
      "Gjysem Cizme",
      "Kepuce te thella",
      "Kepuce",
    ],
    rules: [
      "is",
      "is not",
      "starts with",
      "ends with",
      "contains",
      "does not contain",
    ],
  },
  "Size All": {
    component: Generaltag,
    data: [
      "35",
      "36",
      "37",
      "38",
      "38.5",
      "39",
      "40",
      "41",
      "41.5",
      "42",
      "42.5",
      "43",
      "44",
      "45",
      "46",
      "X",
    ],
    rules: ["contains", "does not contain"],
  },
  "Size In Stock": {
    component: Generaltag,
    data: [
      "35",
      "36",
      "37",
      "38",
      "38.5",
      "39",
      "40",
      "41",
      "42",
      "42.5",
      "43",
      "44",
      "45",
      "46",
      "X",
    ],
    rules: ["contains", "does not contain"],
  },
  Price: {
    component: PriceNumber,
    rules: ["is", "is not", "between"],
  },
  "Initial Price": {
    component: PriceNumber,
    rules: ["is", "is not", "between"],
  },
  "Total Stock": {
    component: PriceNumber,
    rules: ["is", "is not", "between"],
  },
  "On Sale": {
    component: Generaltag,
    data: ["true", "false"],
    rules: [
      "is",
      "is not",
      "starts with",
      "ends with",
      "contains",
      "does not contain",
    ],
  },
  "Has Image": {
    component: Generaltag,
    data: ["true", "false"],
    rules: [],
  },
};

export default inputMapper;
